version: "3.0"
services:
  inception_box:
    privileged: true
    image: inception_box
    environment:
      DOCKER_HOST: https://127.0.0.1
    ports: 
      - 80:8080
    volumes:
      - ./workspace/:/home/ubuntu/
      